import { PLAN_STATUS } from "../../constants/training.js";
import { ROLES } from "../../constants/roles.js";
import { historyView } from "../../services/historyView.js";
import { isAssigned,clubToday } from "../../services/workflowHelpers.js";
import { useMutation } from "../../context/useMutation.js";
import { useCallback, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { useAuth } from "../../context/useAuth.js";
import { useRegistrationResource } from "../../context/useRegistrationResource.js";
import { listHorses,getHorse } from "../../services/clubService.js";
import { listPlans,listTemplates,createPlan,getPlan,editPlan,changePlanStatus,planHistory } from "../../services/trainingService.js";
import { PageHeading,ResourceState,Pagination,BackLink,StateBadge,Field,MutationState} from "../../components/WorkflowUI.jsx";
async function collect(load) { const items = []; for(let page=1;;page++) {const data = await load({page,pageSize:100});items.push(...data.items);if(!data.items.length || data.page*data.pageSize>=data.total) return items;} }
export function PlanList() {
    const {user} = useAuth(); const [search] = useSearchParams(); const [page,setPage] = useState(1);
    const horseId = search.get("horseId") || undefined;
    const load = useCallback(() => listPlans({page,pageSize:20,...(horseId && {horseId})}),[page,horseId]);
    const resource = useRegistrationResource(load);
    return <section className="training-page"><PageHeading title="Kế hoạch huấn luyện" description="Kế hoạch cá nhân hóa và tiến độ các buổi tập." action={user.role === ROLES.Trainer && <Link className="btn btn-primary" to={`/training/plans/new${horseId ? `?horseId=${horseId}` : ""}`}>Tạo kế hoạch</Link>} /><section className="surface-card"><ResourceState resource={resource} />{resource.data && <><div className="table-responsive"><table className="table"><thead><tr><th>Mục tiêu</th><th>Giai đoạn</th><th>Từ ngày</th><th>Đến ngày</th><th>Trạng thái</th><th /></tr></thead><tbody>{resource.data.items.map(plan => <tr key={plan.id}><td>{plan.goal}</td><td>{plan.phase}</td><td>{plan.startDate}</td><td>{plan.endDate}</td><td><StateBadge value={plan.status} /></td><td><Link className="btn btn-outline-primary" to={`/training/plans/${plan.id}`}>Xem kế hoạch</Link></td></tr>)}</tbody></table>{!resource.data.items.length && <p className="empty-state">Chưa có kế hoạch trong phạm vi của bạn.</p>}</div><Pagination data={resource.data} onChange={setPage} /></>}</section></section>;
}
export function PlanCreate() {
    const navigate = useNavigate(); const [search] = useSearchParams();
    const [form,setForm] = useState({horseId:search.get("horseId") || "",templateId:"",goal:"",phase:"",startDate:clubToday(),endDate:clubToday(),notes:""});
    const load = useCallback(async () => ({horses:await collect(listHorses),templates:await collect(listTemplates)}),[]);
    const resource = useRegistrationResource(load); const mutation = useMutation();
    function change(e) { const {name,value} = e.target; if(name === "templateId") {const t = resource.data.templates.find(t => t.id === value);setForm({...form,templateId:value,goal:t?.goal || "",phase:t?.phase || ""});}else setForm({...form,[name]:value}); }
    async function submit(e) {e.preventDefault(); await mutation.run(() => createPlan(form),plan => navigate(`/training/plans/${plan.id}`));}
    return <section className="training-page"><BackLink to="/training/plans">Kế hoạch huấn luyện</BackLink><PageHeading title="Tạo kế hoạch cá nhân hóa" description="Chọn ngựa đang phụ trách và giáo án tham khảo." /><ResourceState resource={resource} /><MutationState mutation={mutation} reload={resource.reload} />{resource.data && <form className="surface-card" onSubmit={submit}><fieldset disabled={mutation.pending || mutation.uncertain}><div className="row g-3"><Field label="Ngựa được phân công" name="horseId" value={form.horseId} onChange={change} required options={[{value:"",label:"Chọn ngựa"},...resource.data.horses.map(h => ({value:h.id,label:h.name}))]} /><Field label="Giáo án tham khảo" name="templateId" value={form.templateId} onChange={change} required options={[{value:"",label:"Chọn giáo án"},...resource.data.templates.map(t => ({value:t.id,label:t.name}))]} /><PlanFields form={form} onChange={change} /></div><div className="wizard-actions"><Link className="btn btn-outline-primary" to="/training/plans">Hủy</Link><button className="btn btn-success">Tạo kế hoạch</button></div></fieldset></form>}</section>;
}
function PlanFields({form,onChange}) {return <><Field label="Mục tiêu" name="goal" value={form.goal} onChange={onChange} required /><Field label="Giai đoạn" name="phase" value={form.phase} onChange={onChange} required /><Field label="Ngày bắt đầu" name="startDate" value={form.startDate} onChange={onChange} type="date" required /><Field label="Ngày kết thúc" name="endDate" value={form.endDate} onChange={onChange} type="date" min={form.startDate} required /><Field label="Ghi chú" name="notes" value={form.notes} onChange={onChange} multiline wide /></>;}
function History({id}) {const [page,setPage]=useState(1);const load=useCallback(()=>planHistory(id,{page,pageSize:20}),[id,page]);const resource=useRegistrationResource(load);return <section className="surface-card"><h2>Lịch sử huấn luyện</h2><ResourceState resource={resource}/>{resource.data && <>{resource.data.items.map(item => <div className="history-item" key={item.id}><div className="muted-caption">{new Date(item.createdAt).toLocaleString("vi-VN",{timeZone:"Asia/Ho_Chi_Minh"})} · {item.sessionId ? "Buổi tập" : "Kế hoạch"}</div><HistorySnapshot snapshot={item.snapshot} /></div>)}{!resource.data.items.length && <p>Chưa có lịch sử.</p>}<Pagination data={resource.data} onChange={setPage}/></>}</section>;}
function HistorySnapshot({snapshot}) {const view=historyView(snapshot);return view ? <details><summary>{view.title} · <StateBadge value={view.status}/></summary><dl className="summary-grid mt-3">{view.rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></details> : <p>Thông tin lịch sử chưa đọc được.</p>;}
function PlanContent({data,horse,user,id,reload}) {
    const [tab,setTab]=useState("sessions");const [editing,setEditing]=useState(false);const [status,setStatus]=useState("");
    const plan=data.plan; const canWrite=isAssigned(horse,user,ROLES.Trainer) && [PLAN_STATUS.Active,PLAN_STATUS.Paused].includes(plan.status);
    const [form,setForm]=useState({horseId:plan.horseId,templateId:plan.templateId,goal:plan.goal,phase:plan.phase,startDate:plan.startDate,endDate:plan.endDate,notes:plan.notes});
    const mutation=useMutation();
    return <><PageHeading title={plan.goal} description={`${horse.horse.name} · ${plan.phase} · ${plan.startDate} → ${plan.endDate}`} action={<StateBadge value={plan.status}/>} /><MutationState mutation={mutation} reload={reload}/>
        {!!data.restrictions.length && <section className="surface-card restriction-card"><h2>Hạn chế vận động</h2>{data.restrictions.map(r=><p key={r.id}>{r.reason} · {r.validFrom?.slice(0,10)} → {r.validUntil?.slice(0,10) || "Chưa có ngày kết thúc"}</p>)}<p className="muted-caption">Điều kiện vận động được kiểm tra lại khi tạo, sửa và bắt đầu buổi tập.</p></section>}
        {canWrite && <section className="surface-card"><div className="inline-actions"><button className="btn btn-outline-primary" disabled={mutation.pending} onClick={()=>setEditing(!editing)}>Chỉnh sửa kế hoạch</button>{plan.status === PLAN_STATUS.Active && <Link className="btn btn-primary" to={`/training/plans/${id}/sessions/new`}>Tạo buổi tập</Link>}</div>{editing && <form className="mt-3" onSubmit={e=>{e.preventDefault();mutation.run(()=>editPlan(id,form),()=>{setEditing(false);reload();});}}><fieldset disabled={mutation.pending || mutation.uncertain}><div className="row g-3"><PlanFields form={form} onChange={e=>setForm({...form,[e.target.name]:e.target.value})}/></div><button className="btn btn-success mt-3">Lưu kế hoạch</button></fieldset></form>}<form className="filter-row mt-3" onSubmit={e=>{e.preventDefault();if(status)mutation.run(()=>changePlanStatus(id,status),reload);}}><div><label className="form-label" htmlFor="plan-status">Đổi trạng thái</label><select id="plan-status" className="form-select" value={status} onChange={e=>setStatus(e.target.value)} disabled={mutation.pending || mutation.uncertain}><option value="">Chọn trạng thái</option>{[PLAN_STATUS.Active,PLAN_STATUS.Paused,PLAN_STATUS.Completed,PLAN_STATUS.Archived].filter(s=>s!==plan.status).map(s=><option key={s} value={s}>{s}</option>)}</select></div><button className="btn btn-outline-primary" disabled={!status || mutation.pending || mutation.uncertain}>Xác nhận</button></form></section>}
        <nav className="section-tabs" aria-label="Kế hoạch"><button className={`btn ${tab === "sessions" ? "btn-primary" : "btn-outline-primary"}`} onClick={()=>setTab("sessions")}>Các buổi tập</button>{user.role !== ROLES.WorkRider && <button className={`btn ${tab === "history" ? "btn-primary" : "btn-outline-primary"}`} onClick={()=>setTab("history")}>Lịch sử</button>}</nav>
        {tab === "sessions" ? <SessionTable data={data}/> : <History id={id}/>}
    </>;
}
function SessionTable({data}) {return <div className="surface-card"><div className="table-responsive"><table className="table"><thead><tr><th>Thời gian (Việt Nam)</th><th>Loại tập</th><th>Quãng đường</th><th>Cường độ</th><th>Trạng thái</th><th/></tr></thead><tbody>{data.sessions.map(s=><tr key={s.id}><td>{new Date(s.scheduledAt).toLocaleString("vi-VN",{timeZone:"Asia/Ho_Chi_Minh"})}</td><td>{s.trainingType}</td><td>{s.distanceMetres} m</td><td>{s.intensity}</td><td><StateBadge value={s.status}/></td><td><Link className="btn btn-outline-primary" to={`/training/sessions/${s.id}`}>Chi tiết</Link></td></tr>)}</tbody></table>{!data.sessions.length && <p className="empty-state">Chưa có buổi tập ở trang này.</p>}</div></div>;}
export function PlanDetail() {
    const {id}=useParams();const {user}=useAuth();const [page,setPage]=useState(1);
    const load=useCallback(async()=>{const plan=await getPlan(id,{sessionPage:page,sessionPageSize:20});return {plan,horse:await getHorse(plan.plan.horseId)};},[id,page]);
    const resource=useRegistrationResource(load);
    return <section className="training-page"><BackLink to="/training/plans">Kế hoạch huấn luyện</BackLink><ResourceState resource={resource}/>{resource.data && <><PlanContent key={`${id}-${resource.data.plan.plan.version}`} id={id} data={resource.data.plan} horse={resource.data.horse} user={user} reload={resource.reload}/><Pagination data={{page:resource.data.plan.sessionPage,pageSize:resource.data.plan.sessionPageSize,total:resource.data.plan.sessionTotal}} onChange={setPage}/></>}</section>;
}
