import { PLAN_STATUS, SESSION_STATUS, INTENSITY, TRAINING_TYPE } from "../../constants/training.js";
import { ROLES } from "../../constants/roles.js";
import { sessionPayload } from "../../services/trainingPayload.js";
import { isAssigned,localDateTime } from "../../services/workflowHelpers.js";
import { useMutation } from "../../context/useMutation.js";
import { useCallback, useState } from "react";
import { Link,useNavigate,useParams } from "react-router-dom";
import { useAuth } from "../../context/useAuth.js";
import { useRegistrationResource } from "../../context/useRegistrationResource.js";
import { getHorse,staffDirectory } from "../../services/clubService.js";
import { getPlan,createSession,listSessions,getSession,editSession,startSession,skipSession,submitResult,evaluateSession } from "../../services/trainingService.js";
import { PageHeading,ResourceState,Pagination,BackLink,Field,StateBadge,MutationState} from "../../components/WorkflowUI.jsx";
const trainingTypes=Object.values(TRAINING_TYPE);
const intensityOptions=Object.values(INTENSITY);

function SessionFields({form,change,riders,disabled,min,max}) {return <fieldset disabled={disabled}><div className="row g-3"><Field label="Thời gian (giờ Việt Nam, UTC+7)" name="scheduledAt" value={form.scheduledAt} onChange={change} type="datetime-local" min={min && `${min}T00:00`} max={max && `${max}T23:59`} required/><Field label="Loại bài tập" name="trainingType" value={form.trainingType} onChange={change} options={trainingTypes}/><Field label="Quãng đường (m)" name="distanceMetres" value={form.distanceMetres} onChange={change} type="number" min={1} max={100000} step="any" required/><Field label="Cường độ" name="intensity" value={form.intensity} onChange={change} options={intensityOptions}/><Field label="Mặt sân" name="surface" value={form.surface} onChange={change} required/><Field label="Mục tiêu buổi tập" name="target" value={form.target} onChange={change} required/><Field label="Work Rider" name="riderId" value={form.riderId} onChange={change} options={[{value:"",label:"Chưa phân công (Planned)"},...riders.map(r=>({value:r.id,label:[r.firstName,r.lastName].filter(Boolean).join(" ")}))]}/><Field label="Ghi chú" name="notes" value={form.notes} onChange={change} multiline/></div></fieldset>;}
export function SessionCreate() {
    const {id}=useParams();const navigate=useNavigate();const {user}=useAuth();
    const [form,setForm]=useState({scheduledAt:"",trainingType:TRAINING_TYPE.Trot,distanceMetres:1000,intensity:INTENSITY.Light,surface:"Sand",target:"",notes:"",riderId:""});
    const load=useCallback(async()=>{const data=await getPlan(id);return {plan:data.plan,horse:await getHorse(data.plan.horseId),riders:await staffDirectory(ROLES.WorkRider),restrictions:data.restrictions};},[id]);
    const resource=useRegistrationResource(load);const mutation=useMutation();
    return <section className="training-page"><BackLink to={`/training/plans/${id}`}>Kế hoạch huấn luyện</BackLink><PageHeading title="Tạo buổi tập" description="Có thể giao Rider ngay hoặc lưu buổi tập ở trạng thái Planned."/><ResourceState resource={resource}/><MutationState mutation={mutation} reload={resource.reload}/>{resource.data && (isAssigned(resource.data.horse,user,ROLES.Trainer) && resource.data.plan.status === PLAN_STATUS.Active ? <form className="surface-card" onSubmit={e=>{e.preventDefault();mutation.run(()=>createSession(id,sessionPayload(form)),s=>navigate(`/training/sessions/${s.id}`));}}><SessionFields form={form} change={e=>setForm({...form,[e.target.name]:e.target.value})} riders={resource.data.riders} min={resource.data.plan.startDate} max={resource.data.plan.endDate} disabled={mutation.pending || mutation.uncertain}/><div className="wizard-actions"><button className="btn btn-success" disabled={mutation.pending || mutation.uncertain}>Lưu buổi tập</button></div></form> : <p className="alert alert-warning">Chỉ Trainer đang được phân công có thể tạo buổi tập khi Plan đang Active.</p>)}</section>;
}
export function SessionList() {
    const [filter,setFilter]=useState({page:1,pageSize:20,status:""});
    const load=useCallback(()=>listSessions({...filter,status:filter.status || undefined}),[filter]);const resource=useRegistrationResource(load);
    return <section className="training-page"><PageHeading title="Các buổi tập" description="Theo dõi buổi tập trong phạm vi của bạn."/><section className="surface-card"><label htmlFor="session-filter" className="form-label">Trạng thái</label><select id="session-filter" className="form-select mb-3" value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value,page:1})}>{["",SESSION_STATUS.Planned,SESSION_STATUS.Assigned,SESSION_STATUS.InProgress,SESSION_STATUS.Completed,SESSION_STATUS.Skipped,SESSION_STATUS.IssueReported].map(s=><option key={s} value={s}>{s || "Tất cả"}</option>)}</select><ResourceState resource={resource}/>{resource.data && <><div className="table-responsive"><table className="table"><thead><tr><th>Thời gian</th><th>Bài tập</th><th>Quãng đường</th><th>Trạng thái</th><th/></tr></thead><tbody>{resource.data.items.map(s=><tr key={s.id}><td>{new Date(s.scheduledAt).toLocaleString("vi-VN",{timeZone:"Asia/Ho_Chi_Minh"})}</td><td>{s.trainingType}</td><td>{s.distanceMetres} m</td><td><StateBadge value={s.status}/></td><td><Link className="btn btn-outline-primary" to={`/training/sessions/${s.id}`}>Chi tiết</Link></td></tr>)}</tbody></table>{!resource.data.items.length && <p className="empty-state">Không có buổi tập ở trạng thái này.</p>}</div><Pagination data={resource.data} onChange={page=>setFilter({...filter,page})}/></>}</section></section>;
}
function SessionContent({data,reload,user}) {
    const s=data.session;const plan=data.plan;const writer=isAssigned(data.horse,user,ROLES.Trainer);
    const rider=user.role === ROLES.WorkRider && s.riderId === user.id;
    const [editing,setEditing]=useState(false);const [reason,setReason]=useState("");
    const [form,setForm]=useState({...s,scheduledAt:localDateTime(s.scheduledAt),riderId:s.riderId || ""});
    const [result,setResult]=useState({distanceMetres:s.distanceMetres,timeSeconds:"",heartRate:"",intensity:s.intensity,feedback:"",abnormalObservation:false});
    const [evaluation,setEvaluation]=useState({comment:"",adjustFutureSessions:false});
    const mutation=useMutation();const locked=mutation.pending || mutation.uncertain;
    return <><PageHeading title={`${data.horse.horse.name} · ${s.trainingType}`} description={new Date(s.scheduledAt).toLocaleString("vi-VN",{timeZone:"Asia/Ho_Chi_Minh"})} action={<StateBadge value={s.status}/>}/><MutationState mutation={mutation} reload={reload}/><section className="surface-card"><h2>Thông tin buổi tập</h2><dl className="summary-grid">{[["Quãng đường",`${s.distanceMetres} m`],["Cường độ",s.intensity],["Mặt sân",s.surface],["Mục tiêu",s.target],["Rider",s.riderId ? (s.riderId === user.id ? "Bạn" : "Đã được phân công") : "Chưa phân công"],["Ghi chú",s.notes]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value || "—"}</dd></div>)}</dl></section>
        {writer && [SESSION_STATUS.Planned,SESSION_STATUS.Assigned].includes(s.status) && plan.status === PLAN_STATUS.Active && <section className="surface-card"><h2>Điều chỉnh và phân công Rider</h2><button className="btn btn-outline-primary" disabled={locked} onClick={()=>setEditing(!editing)}>Chỉnh sửa buổi tập</button>{editing && <form className="mt-3" onSubmit={e=>{e.preventDefault();mutation.run(()=>editSession(s.id,sessionPayload(form)),reload);}}><SessionFields form={form} change={e=>setForm({...form,[e.target.name]:e.target.value})} riders={data.riders} min={plan.startDate} max={plan.endDate} disabled={locked}/><button className="btn btn-success mt-3" disabled={locked}>Lưu điều chỉnh</button></form>}</section>}
        {rider && s.status === SESSION_STATUS.Assigned && <section className="surface-card"><h2>Thực hiện buổi tập</h2><p>Kiểm tra thông tin buổi tập trước khi bắt đầu.</p><button className="btn btn-success" disabled={locked || plan.status !== PLAN_STATUS.Active} onClick={()=>mutation.run(()=>startSession(s.id),reload,"Đã bắt đầu buổi tập.")}>Bắt đầu buổi tập</button></section>}
        {rider && s.status === SESSION_STATUS.InProgress && !data.result && <section className="surface-card"><h2>Ghi nhận kết quả</h2><form onSubmit={e=>{e.preventDefault();mutation.run(()=>submitResult(s.id,{...result,distanceMetres:Number(result.distanceMetres),timeSeconds:Number(result.timeSeconds),heartRate:result.heartRate === "" ? null : Number(result.heartRate)}),reload,"Đã lưu kết quả buổi tập.");}}><fieldset disabled={locked}><div className="row g-3"><Field label="Quãng đường thực tế (m)" name="distanceMetres" value={result.distanceMetres} onChange={e=>setResult({...result,[e.target.name]:e.target.value})} type="number" min={0} max={100000} step="any" required/><Field label="Thời gian (giây)" name="timeSeconds" value={result.timeSeconds} onChange={e=>setResult({...result,[e.target.name]:e.target.value})} type="number" min={0.001} max={86400} step="any" required/><Field label="Nhịp tim (không bắt buộc)" name="heartRate" value={result.heartRate} onChange={e=>setResult({...result,[e.target.name]:e.target.value})} type="number" min={1} max={300}/><Field label="Cường độ thực tế" name="intensity" value={result.intensity} onChange={e=>setResult({...result,[e.target.name]:e.target.value})} options={intensityOptions}/><Field label="Nhận xét của Rider" name="feedback" value={result.feedback} onChange={e=>setResult({...result,feedback:e.target.value})} multiline wide required/></div><label className="d-flex gap-2 mt-3"><input type="checkbox" checked={result.abnormalObservation} onChange={e=>setResult({...result,abnormalObservation:e.target.checked})}/>Ghi nhận biểu hiện bất thường</label><button className="btn btn-success mt-3">Gửi kết quả</button></fieldset></form></section>}
        {data.result && <section className="surface-card"><h2>Kết quả buổi tập</h2><dl className="summary-grid">{[["Quãng đường",`${data.result.distanceMetres} m`],["Thời gian",`${data.result.timeSeconds} giây`],["Tốc độ",`${data.result.speedMetresPerSecond} m/s`],["Nhịp tim",data.result.heartRate || "—"],["Phản hồi",data.result.feedback],["Bất thường",data.result.abnormalObservation ? "Có" : "Không"]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>}
        {writer && data.result && [SESSION_STATUS.Completed,SESSION_STATUS.IssueReported].includes(s.status) && !data.evaluation && <section className="surface-card"><h2>Đánh giá của Trainer</h2><form onSubmit={e=>{e.preventDefault();mutation.run(()=>evaluateSession(s.id,evaluation),reload,"Đã lưu đánh giá.");}}><fieldset disabled={locked}><label htmlFor="evaluation-comment" className="form-label">Nhận xét và quyết định</label><textarea id="evaluation-comment" className="form-control" required rows={4} value={evaluation.comment} onChange={e=>setEvaluation({...evaluation,comment:e.target.value})}/><label className="d-flex gap-2 mt-3"><input type="checkbox" checked={evaluation.adjustFutureSessions} onChange={e=>setEvaluation({...evaluation,adjustFutureSessions:e.target.checked})}/>Đề nghị điều chỉnh các buổi tập tương lai</label><p className="muted-caption mt-2">Lựa chọn này ghi nhận ý định điều chỉnh. Trainer cần sửa từng buổi tập tương lai để áp dụng.</p><button className="btn btn-success">Lưu đánh giá</button></fieldset></form></section>}
        {data.evaluation && <section className="surface-card"><h2>Đánh giá đã lưu</h2><p style={{whiteSpace:"pre-wrap"}}>{data.evaluation.comment}</p><p className="muted-caption">{data.evaluation.adjustFutureSessions ? "Có đề nghị điều chỉnh các buổi tập tương lai." : "Tiếp tục theo kế hoạch hiện tại."}</p></section>}
        {(writer || rider) && [SESSION_STATUS.Planned,SESSION_STATUS.Assigned,SESSION_STATUS.InProgress].includes(s.status) && <section className="surface-card"><h2>Bỏ qua buổi tập</h2><form onSubmit={e=>{e.preventDefault();if(reason.trim())mutation.run(()=>skipSession(s.id,reason.trim()),reload);}}><label htmlFor="skip-reason" className="form-label">Lý do</label><textarea id="skip-reason" className="form-control mb-3" value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000} required disabled={locked}/><button className="btn btn-outline-danger" disabled={locked || !reason.trim()}>Xác nhận bỏ qua</button></form></section>}
    </>;
}
export function SessionDetail() {
    const {id}=useParams();const {user}=useAuth();
    const load=useCallback(async()=>{const data=await getSession(id);const horse=await getHorse(data.session.horseId);const plan=await getPlan(data.session.planId);const riders=isAssigned(horse,user,ROLES.Trainer) ? await staffDirectory(ROLES.WorkRider) : [];return {...data,horse,plan:plan.plan,riders};},[id,user]);
    const resource=useRegistrationResource(load);
    return <section className="training-page"><BackLink to="/training/sessions">Danh sách buổi tập</BackLink><ResourceState resource={resource}/>{resource.data && <SessionContent key={`${id}-${resource.data.session.version}`} data={resource.data} user={user} reload={resource.reload}/>}</section>;
}
