import { INTENSITY } from "../../constants/training.js";
import { ROLES } from "../../constants/roles.js";
import { useMutation } from "../../context/useMutation.js";
import { useCallback, useState } from "react";
import { useAuth } from "../../context/useAuth.js";
import { useRegistrationResource } from "../../context/useRegistrationResource.js";
import { listTemplates,createTemplate,editTemplate,archiveTemplate } from "../../services/trainingService.js";
import { PageHeading,ResourceState,Pagination,Field,MutationState } from "../../components/WorkflowUI.jsx";
const TEMPLATE_DEFAULT = {name:"",goal:"",phase:"",distanceMetres:1000,intensity:INTENSITY.Light,surface:"Sand",frequencyPerWeek:3,notes:""};
export function TemplateForm({form,onChange,disabled}) { return <fieldset disabled={disabled}><div className="row g-3"><Field label="Tên giáo án" name="name" value={form.name} onChange={onChange} required maxLength={200} /><Field label="Mục tiêu" name="goal" value={form.goal} onChange={onChange} required /><Field label="Giai đoạn" name="phase" value={form.phase} onChange={onChange} required /><Field label="Quãng đường (m)" name="distanceMetres" value={form.distanceMetres} onChange={onChange} required type="number" min={1} max={100000} step="any" /><Field label="Cường độ" name="intensity" value={form.intensity} onChange={onChange} options={Object.values(INTENSITY)} /><Field label="Mặt sân" name="surface" value={form.surface} onChange={onChange} required /><Field label="Số buổi mỗi tuần" name="frequencyPerWeek" value={form.frequencyPerWeek} onChange={onChange} required type="number" min={1} max={21} /><Field label="Ghi chú" name="notes" value={form.notes} onChange={onChange} multiline /></div></fieldset>; }
export function TemplateList() {
    const {user} = useAuth();
    const [page,setPage] = useState(1);
    const [editing,setEditing] = useState(null);
    const [form,setForm] = useState(TEMPLATE_DEFAULT);
    const [confirmArchive,setConfirmArchive] = useState(null);
    const load = useCallback(() => listTemplates({page,pageSize:20}),[page]);
    const resource = useRegistrationResource(load);
    const mutation = useMutation();
    const canEdit = user.role === ROLES.HeadTrainer;
    function open(record) { mutation.reset();setEditing(record?.id || "new");setForm(record ? Object.fromEntries(Object.keys(TEMPLATE_DEFAULT).map(k => [k,record[k] ?? TEMPLATE_DEFAULT[k]])) : TEMPLATE_DEFAULT); }
    async function submit(e) { e.preventDefault(); const payload = {...form,distanceMetres:Number(form.distanceMetres),frequencyPerWeek:Number(form.frequencyPerWeek)}; await mutation.run(() => editing === "new" ? createTemplate(payload) : editTemplate(editing,payload),() => { setEditing(null);resource.reload(); }); }
    return <section className="training-page"><PageHeading title="Giáo án huấn luyện tiêu chuẩn" description="Khung tham khảo để Trainer xây dựng kế hoạch cá nhân hóa." action={canEdit && <button className="btn btn-primary" onClick={() => open(null)} disabled={mutation.pending}>Tạo giáo án</button>} /><MutationState mutation={mutation} reload={resource.reload} />{editing && <section className="surface-card"><h2>{editing === "new" ? "Tạo giáo án" : "Chỉnh sửa giáo án"}</h2><form onSubmit={submit}><TemplateForm form={form} onChange={e => setForm({...form,[e.target.name]:e.target.value})} disabled={mutation.pending || mutation.uncertain} /><div className="wizard-actions"><button type="button" className="btn btn-outline-primary" disabled={mutation.pending} onClick={() => setEditing(null)}>Hủy</button><button className="btn btn-success" disabled={mutation.pending || mutation.uncertain}>Lưu giáo án</button></div></form></section>}<section className="surface-card"><ResourceState resource={resource} />{resource.data && <><div className="table-responsive"><table className="table"><thead><tr><th>Giáo án</th><th>Mục tiêu</th><th>Quãng đường</th><th>Cường độ</th><th>Buổi/tuần</th>{canEdit && <th />}</tr></thead><tbody>{resource.data.items.map(t => <tr key={t.id}><td>{t.name}</td><td>{t.goal}</td><td>{t.distanceMetres} m</td><td>{t.intensity}</td><td>{t.frequencyPerWeek}</td>{canEdit && <td><div className="inline-actions"><button className="btn btn-outline-primary" disabled={mutation.pending} onClick={() => open(t)}>Chỉnh sửa</button><button className="btn btn-outline-danger" disabled={mutation.pending || mutation.uncertain} onClick={() => setConfirmArchive(t)}>Lưu trữ</button></div></td>}</tr>)}</tbody></table>{!resource.data.items.length && <p className="empty-state">Chưa có giáo án tiêu chuẩn.</p>}</div><Pagination data={resource.data} onChange={setPage} /></>}</section>{confirmArchive && <div className="surface-card"><p>Lưu trữ giáo án “{confirmArchive.name}”? Các Plan đã tạo vẫn được giữ lại.</p><div className="inline-actions"><button className="btn btn-outline-primary" disabled={mutation.pending} onClick={() => setConfirmArchive(null)}>Giữ giáo án</button><button className="btn btn-primary" disabled={mutation.pending || mutation.uncertain} onClick={() => mutation.run(() => archiveTemplate(confirmArchive.id),() => {setConfirmArchive(null);resource.reload();})}>Xác nhận lưu trữ</button></div></div>}</section>;
}
