import api from "./api.js";
const path = (kind, id) => `/api/training/${kind}${id ? `/${encodeURIComponent(id)}` : ""}`;
export const listTemplates = params => api.get(path("templates"), { params }).then(r => r.data);
export const createTemplate = request => api.post(path("templates"), request).then(r => r.data);
export const editTemplate = (id, request) => api.put(path("templates", id), request).then(r => r.data);
export const archiveTemplate = id => api.post(`${path("templates", id)}/archive`).then(r => r.data);
export const listPlans = params => api.get(path("plans"), { params }).then(r => r.data);
export const createPlan = request => api.post(path("plans"), request).then(r => r.data);
export const getPlan = (id, params) => api.get(path("plans", id), { params }).then(r => r.data);
export const editPlan = (id, request) => api.put(path("plans", id), request).then(r => r.data);
export const changePlanStatus = (id, status) => api.put(`${path("plans", id)}/status`, { status }).then(r => r.data);
export const planHistory = (id, params) => api.get(`${path("plans", id)}/history`, { params }).then(r => r.data);
export const createSession = (id, request) => api.post(`${path("plans", id)}/sessions`, request).then(r => r.data);
export const listSessions = params => api.get(path("sessions"), { params }).then(r => r.data);
export const getSession = id => api.get(path("sessions", id)).then(r => r.data);
export const editSession = (id, request) => api.put(path("sessions", id), request).then(r => r.data);
export const assignRider = (id, riderId) => api.post(`${path("sessions", id)}/assign`, { riderId }).then(r => r.data);
export const startSession = id => api.post(`${path("sessions", id)}/start`).then(r => r.data);
export const skipSession = (id, reason) => api.post(`${path("sessions", id)}/skip`, { reason }).then(r => r.data);
export const submitResult = (id, request) => api.post(`${path("sessions", id)}/results`, request).then(r => r.data);
export const evaluateSession = (id, request) => api.post(`${path("sessions", id)}/evaluation`, request).then(r => r.data);
