import {useCallback,useState} from 'react';
import {MSG,msg,UI_LOCALE} from '../../messages/index.js';
import {useRegistrationResource} from '../../context/useRegistrationResource.js';
import {PageHeading,ResourceState,Pagination} from '../../components/WorkflowUI.jsx';
import {auditLabel} from '../../constants/audit.js';
import {listAudit} from '../../services/managerService.js';
export default function AuditPage(){const [form,setForm]=useState({search:'',from:'',to:''}),[filter,setFilter]=useState({page:1,pageSize:20});const load=useCallback(()=>listAudit(filter),[filter]);const resource=useRegistrationResource(load);
 return <section><PageHeading title={msg(MSG.ADMIN_AUDIT)} description={msg(MSG.ADMIN_AUDIT_HELP)}/><div className="surface-card"><form className="filter-row" onSubmit={e=>{e.preventDefault();setFilter({...form,page:1,pageSize:20});}}>{[['search',MSG.ADMIN_ACTOR],['from',MSG.ADMIN_FROM],['to',MSG.ADMIN_TO]].map(([name,label])=><div key={name}><label className="form-label" htmlFor={'audit-'+name}>{msg(label)}</label><input id={'audit-'+name} className="form-control" type={name==='search'?'text':'date'} maxLength={100} value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})}/></div>)}<button className="btn btn-primary">{msg(MSG.SEARCH_ACTION)}</button><button type="button" className="btn btn-outline-secondary" onClick={()=>{setForm({search:'',from:'',to:''});setFilter({page:1,pageSize:20});}}>{msg(MSG.SEARCH_CLEAR)}</button></form><ResourceState resource={resource}/>{resource.data && <><div className="table-responsive"><table className="table"><thead><tr>{[MSG.THOI_GIAN,MSG.ADMIN_ACTOR,MSG.ADMIN_ACTION,MSG.ADMIN_REFERENCE].map(k=><th key={k}>{msg(k)}</th>)}</tr></thead><tbody>{resource.data.items.map(a=><tr key={a.id}><td>{new Date(a.createdAt).toLocaleString(UI_LOCALE,{timeZone:'Asia/Ho_Chi_Minh'})}</td><td>{a.actorName || msg(MSG.CHUA_CO_THONG_TIN)}</td><td>{auditLabel(a.action)}</td><td>{a.action.startsWith('Website')?msg(MSG.ADMIN_WEBSITE):a.referenceId}<details><summary>{msg(MSG.CHI_TIET)}</summary><pre>{a.detail}</pre></details></td></tr>)}</tbody></table></div>{!resource.data.items.length && <p>{msg(MSG.ADMIN_EMPTY)}</p>}<Pagination data={resource.data} onChange={page=>setFilter({...filter,page})}/></>}</div></section>;
}
