import {useCallback,useState} from 'react';
import {MSG,msg} from '../../messages/index.js';
import {ALL_ROLES,ROLES,getRoleLabel} from '../../constants/roles.js';
import {useRegistrationResource} from '../../context/useRegistrationResource.js';
import {useMutation} from '../../context/useMutation.js';
import {PageHeading,ResourceState,Pagination,Field,MutationState} from '../../components/WorkflowUI.jsx';
import {listStaff,inviteStaff,resendStaff} from '../../services/managerService.js';
const empty={email:'',userName:'',firstName:'',lastName:'',phone:'',address:'',role:ROLES.Trainer};
export default function StaffPage(){
 const [filter,setFilter]=useState({page:1,pageSize:20,role:''}),[form,setForm]=useState(empty);
 const load=useCallback(()=>listStaff({...filter,role:filter.role || undefined}),[filter]);const resource=useRegistrationResource(load);const mutation=useMutation();
 const options=ALL_ROLES.filter(r=>r!==ROLES.HorseOwner).map(value=>({value,label:getRoleLabel(value)}));
 return <section><PageHeading title={msg(MSG.ADMIN_STAFF)} description={msg(MSG.ADMIN_INVITE_HELP)}/><section className="surface-card"><h2>{msg(MSG.ADMIN_INVITE)}</h2><MutationState mutation={mutation} reload={resource.reload}/><form onSubmit={e=>{e.preventDefault();mutation.run(()=>inviteStaff(form),()=>{setForm(empty);resource.reload();},msg(MSG.ADMIN_INVITED));}}><fieldset disabled={mutation.pending || mutation.uncertain}><div className="row g-3">{[['firstName',MSG.FIRST_NAME],['lastName',MSG.LAST_NAME],['email',MSG.EMAIL],['userName',MSG.USERNAME],['phone',MSG.PHONE],['address',MSG.ADDRESS]].map(([name,label])=><Field key={name} name={name} label={msg(label)} value={form[name]} maxLength={name==='address'?500:100} type={name==='email'?'email':'text'} required onChange={e=>setForm({...form,[name]:e.target.value})}/>)}<Field label={msg(MSG.VAI_TRO)} name="role" value={form.role} options={options} onChange={e=>setForm({...form,role:e.target.value})}/></div><button className="btn btn-primary mt-3">{msg(MSG.ADMIN_INVITE)}</button></fieldset></form></section><section className="surface-card"><label className="form-label" htmlFor="staff-role">{msg(MSG.VAI_TRO)}</label><select id="staff-role" className="form-select mb-3" value={filter.role} onChange={e=>setFilter({...filter,role:e.target.value,page:1})}><option value="">{msg(MSG.TAT_CA)}</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select><ResourceState resource={resource}/>{resource.data && <><div className="table-responsive"><table className="table"><thead><tr>{[MSG.ADMIN_NAME,MSG.EMAIL,MSG.VAI_TRO,MSG.ADMIN_ACTIVATION,MSG.TRANG_THAI].map(k=><th key={k}>{msg(k)}</th>)}<th/></tr></thead><tbody>{resource.data.items.map(u=><tr key={u.id}><td>{[u.firstName,u.lastName].filter(Boolean).join(' ') || u.userName}</td><td>{u.email}</td><td>{getRoleLabel(u.role)}</td><td>{msg(u.emailVerified?MSG.ADMIN_ACTIVATED:MSG.ADMIN_PENDING)}</td><td>{msg(u.active?MSG.ADMIN_ENABLED:MSG.ADMIN_DISABLED)}</td><td>{!u.emailVerified && <button className="btn btn-outline-primary" disabled={mutation.pending || mutation.uncertain} onClick={()=>mutation.run(()=>resendStaff(u.id),resource.reload,msg(MSG.ADMIN_SENT))}>{msg(MSG.ADMIN_RESEND)}</button>}</td></tr>)}</tbody></table></div>{!resource.data.items.length && <p>{msg(MSG.ADMIN_EMPTY)}</p>}<Pagination data={resource.data} onChange={page=>setFilter({...filter,page})}/></>}</section></section>;
}
