import {useCallback,useState,useEffect} from 'react';
import {useWebsite} from '../../services/websiteStore.js';
import {MSG,msg} from '../../messages/index.js';
import {useRegistrationResource} from '../../context/useRegistrationResource.js';
import {useMutation} from '../../context/useMutation.js';
import {PageHeading,ResourceState,Field,MutationState} from '../../components/WorkflowUI.jsx';
import {getWebsite,saveWebsite,uploadWebsiteAsset} from '../../services/managerService.js';
const kinds=[['Logo',MSG.ADMIN_LOGO],['Hero',MSG.ADMIN_HERO_IMAGE],['Background',MSG.ADMIN_BACKGROUND]];
function AssetUpload({kind,label,version,onSaved,disabled}){const [file,setFile]=useState(null),[preview,setPreview]=useState('');const mutation=useMutation();
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 return <section className="surface-card"><h2>{msg(label)}</h2><p className="form-text">{msg(MSG.ADMIN_UPLOAD_HELP)}</p>{preview && <img src={preview} alt={msg(label)} style={{maxWidth:'100%',height:160,objectFit:'contain'}}/>}<form onSubmit={e=>{e.preventDefault();mutation.run(()=>uploadWebsiteAsset(kind,file,version),async data=>{await onSaved(data);setFile(null);setPreview('');});}}><label className="form-label" htmlFor={'asset-'+kind}>{msg(label)}</label><input id={'asset-'+kind} type="file" className="form-control" accept="image/png,image/jpeg" disabled={disabled || mutation.pending} onChange={e=>{const selected=e.target.files[0] || null;setFile(selected);setPreview(selected?URL.createObjectURL(selected):'');}}/><button className="btn btn-outline-primary mt-3" disabled={!file || disabled || mutation.pending || mutation.uncertain}>{msg(MSG.ADMIN_UPLOAD)}</button></form><MutationState mutation={mutation} reload={()=>{mutation.reset();onSaved();}}/></section>;
}
function WebsiteEditor({initial,reload}){const [form,setForm]=useState(initial),[preview,setPreview]=useState(false);const mutation=useMutation();
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const saved=async data=>{const latest=data || await getWebsite();setForm(current=>({...current,version:latest.version}));reload();};
 return <><section className="surface-card"><MutationState mutation={mutation} reload={async()=>{setForm(await getWebsite());reload();}}/><form onSubmit={e=>{e.preventDefault();mutation.run(()=>saveWebsite({version:form.version,heroTitle:form.heroTitle,heroDescription:form.heroDescription,featuresTitle:form.featuresTitle,featuresDescription:form.featuresDescription,features:form.features}),data=>{setForm(data);reload();});}}><fieldset disabled={mutation.pending || mutation.uncertain}><div className="row g-3">{[['heroTitle',MSG.ADMIN_HERO_TITLE],['heroDescription',MSG.ADMIN_HERO_BODY],['featuresTitle',MSG.ADMIN_FEATURE_TITLE],['featuresDescription',MSG.ADMIN_FEATURE_BODY]].map(([name,label])=><Field key={name} label={msg(label)} name={name} value={form[name]} onChange={change} multiline={name.endsWith('Description')} maxLength={name.endsWith('Description')?1000:160} required/>)}{form.features.map((feature,index)=><div className="col-12" key={index}><h2>{msg(MSG.ADMIN_FEATURES)} {index+1}</h2><div className="row g-3"><Field label={msg(MSG.ADMIN_FEATURE_NAME)} name={'featureTitle'+index} value={feature.title} maxLength={160} required onChange={e=>setForm({...form,features:form.features.map((f,i)=>i===index?{...f,title:e.target.value}:f)})}/><Field label={msg(MSG.ADMIN_FEATURE_DESCRIPTION)} name={'featureBody'+index} value={feature.description} maxLength={1000} multiline required onChange={e=>setForm({...form,features:form.features.map((f,i)=>i===index?{...f,description:e.target.value}:f)})}/></div></div>)}</div><div className="wizard-actions"><button type="button" className="btn btn-outline-primary" onClick={()=>setPreview(!preview)}>{msg(MSG.ADMIN_PREVIEW)}</button><button type="button" className="btn btn-outline-secondary" onClick={()=>{setForm(initial);setPreview(false);mutation.reset();}}>{msg(MSG.ADMIN_CANCEL)}</button><button className="btn btn-primary">{msg(MSG.ADMIN_SAVE)}</button></div></fieldset></form></section>{preview && <section className="surface-card" aria-label={msg(MSG.ADMIN_PREVIEW)}><h2>{form.heroTitle}</h2><p>{form.heroDescription}</p><h2>{form.featuresTitle}</h2><p>{form.featuresDescription}</p><div className="row g-3">{form.features.map((f,i)=><article className="col-md-4" key={i}><h3>{f.title}</h3><p>{f.description}</p></article>)}</div></section>}<div className="row">{kinds.map(([kind,label])=><div className="col-lg-4" key={kind}><AssetUpload kind={kind} label={label} version={form.version} onSaved={saved} disabled={mutation.pending || mutation.uncertain}/></div>)}</div></>;
}
export default function WebsitePage(){const load=useCallback(()=>getWebsite(),[]);const resource=useRegistrationResource(load);const cached=useWebsite();const data=resource.data || cached;return <section><PageHeading title={msg(MSG.ADMIN_WEBSITE)} description={msg(MSG.ADMIN_WEBSITE_HELP)}/><ResourceState resource={resource}/>{data && <WebsiteEditor initial={data} reload={resource.reload}/>}</section>;}
