import { MSG, msg } from '../messages/index.js';
import { ROLES, getRoleLabel, isKnownRole } from './roles.js';
import { HORSE_GENDER, ATTACHMENT_TYPE, HEALTH_STATUS, REGISTRATION_STATUS } from './registration.js';
import { PLAN_STATUS, SESSION_STATUS, INTENSITY, TRAINING_TYPE } from './training.js';

export const ENUM_MESSAGE_KEYS = Object.freeze({
    [HORSE_GENDER.Male]: MSG.DUC, [HORSE_GENDER.Female]: MSG.CAI, [HORSE_GENDER.Gelding]: MSG.DUC_DA_THIEN,
    [ATTACHMENT_TYPE.HorsePhoto]: MSG.ANH_NGUA, [ATTACHMENT_TYPE.Certificate]: MSG.CHUNG_NHAN, [ATTACHMENT_TYPE.MedicalDocument]: MSG.TAI_LIEU_Y_TE,
    [REGISTRATION_STATUS.Draft]: MSG.BAN_NHAP, [REGISTRATION_STATUS.PendingReview]: MSG.CHO_DUYET, [REGISTRATION_STATUS.RevisionRequired]: MSG.CAN_CHINH_SUA, [REGISTRATION_STATUS.Approved]: MSG.DA_PHE_DUYET, [REGISTRATION_STATUS.Cancelled]: MSG.DA_HUY,
    [PLAN_STATUS.Active]: MSG.DANG_THUC_HIEN, [PLAN_STATUS.Paused]: MSG.TAM_DUNG, [PLAN_STATUS.Completed]: MSG.HOAN_THANH, [PLAN_STATUS.Archived]: MSG.DA_LUU_TRU,
    [SESSION_STATUS.Planned]: MSG.CHUA_GIAO_RIDER, [SESSION_STATUS.Assigned]: MSG.DA_GIAO_RIDER, [SESSION_STATUS.InProgress]: MSG.DANG_TAP, [SESSION_STATUS.Skipped]: MSG.DA_BO_QUA, [SESSION_STATUS.IssueReported]: MSG.CO_VAN_DE,
    [HEALTH_STATUS.Fit]: MSG.DU_SUC_KHOE, [HEALTH_STATUS.Monitoring]: MSG.THEO_DOI, [HEALTH_STATUS.Injured]: MSG.CHAN_THUONG, [HEALTH_STATUS.Isolated]: MSG.CACH_LY,
    [INTENSITY.Light]: MSG.INTENSITY_LIGHT, [INTENSITY.Moderate]: MSG.INTENSITY_MODERATE, [INTENSITY.Heavy]: MSG.INTENSITY_HEAVY,
    [TRAINING_TYPE.Walk]: MSG.TRAINING_WALK, [TRAINING_TYPE.Trot]: MSG.TRAINING_TROT, [TRAINING_TYPE.Canter]: MSG.TRAINING_CANTER, [TRAINING_TYPE.Gallop]: MSG.TRAINING_GALLOP, [TRAINING_TYPE.Sprint]: MSG.TRAINING_SPRINT, [TRAINING_TYPE.Recovery]: MSG.TRAINING_RECOVERY,
});
/** API enum values stay unchanged. Unknown values receive a safe display label. */
export function getEnumLabel(value) {
    if (isKnownRole(value)) return getRoleLabel(value);
    return Object.hasOwn(ENUM_MESSAGE_KEYS, value) ? msg(ENUM_MESSAGE_KEYS[value]) : msg(MSG.CHUA_XAC_DINH);
}
export const ENUMS = Object.freeze({ ROLES, HORSE_GENDER, ATTACHMENT_TYPE, HEALTH_STATUS, REGISTRATION_STATUS, PLAN_STATUS, SESSION_STATUS, INTENSITY, TRAINING_TYPE });
