import { Link } from "react-router-dom";
import RegistrationError from "./registrations/RegistrationError.jsx";

export function PageHeading({ title, description, action, id }) { return <div className="page-heading"><div><h1 id={id}>{title}</h1>{description && <p>{description}</p>}</div>{action}</div>; }
export function ResourceState({ resource }) { return <>{resource.loading && <p role="status">Đang tải dữ liệu...</p>}{resource.error && <><RegistrationError error={resource.error} /><button className="btn btn-outline-primary" onClick={resource.reload}>Tải lại</button></>}</>; }
export function Pagination({ data, onChange }) { return data && <nav aria-label="Phân trang" className="pagination-row"><button className="btn btn-outline-secondary" disabled={data.page <= 1} onClick={() => onChange(data.page - 1)}>Trước</button><span>Trang {data.page} / {Math.max(1, Math.ceil(data.total / data.pageSize))} · {data.total} kết quả</span><button className="btn btn-outline-secondary" disabled={data.page * data.pageSize >= data.total} onClick={() => onChange(data.page + 1)}>Sau</button></nav>; }
export function BackLink({ to, children = "Quay lại" }) { return <Link className="page-back" to={to}>← {children}</Link>; }
export function Field({ label, name, value, onChange, options, multiline, ...props }) {
    const id = `field-${name}`;
    return <div className={props.wide ? "col-12" : "col-md-6"}><label className="form-label" htmlFor={id}>{label}</label>{options ? <select id={id} name={name} className="form-select" value={value ?? ""} onChange={onChange} required={props.required} disabled={props.disabled}>{options.map(option => { const o = typeof option === "string" ? { value: option, label: option } : option; return <option key={o.value} value={o.value}>{o.label}</option>; })}</select> : multiline ? <textarea id={id} name={name} rows={3} className="form-control" value={value ?? ""} onChange={onChange} required={props.required} disabled={props.disabled} maxLength={props.maxLength} /> : <input id={id} name={name} className="form-control" value={value ?? ""} onChange={onChange} type={props.type || "text"} onInput={props.type?.startsWith("date") ? onChange : undefined} required={props.required} min={props.min} max={props.max} step={props.step} disabled={props.disabled} maxLength={props.maxLength} autoComplete={props.autoComplete} />}</div>;
}
export function MutationState({ mutation, reload }) { return <><RegistrationError error={mutation.error} />{mutation.notice && <p className="alert alert-success" role="status">{mutation.notice}</p>}{mutation.pending && <p role="status">Đang xử lý...</p>}{mutation.uncertain && <div className="alert alert-warning">Hãy tải lại dữ liệu trước khi thực hiện thao tác tiếp theo.<button className="btn btn-outline-primary ms-2" onClick={() => { mutation.reset(); reload(); }}>Tải lại</button></div>}</>; }
const display = { Active: "Đang thực hiện", Paused: "Tạm dừng", Completed: "Hoàn thành", Archived: "Đã lưu trữ", Planned: "Chưa giao Rider", Assigned: "Đã giao Rider", InProgress: "Đang tập", Skipped: "Đã bỏ qua", IssueReported: "Có vấn đề", Fit: "Đủ sức khỏe", Monitoring: "Theo dõi", Injured: "Chấn thương", Isolated: "Cách ly" };
export function StateBadge({ value }) { return <span className={`badge status-pill ${["Completed","Fit"].includes(value) ? "text-bg-success" : ["IssueReported","Injured","Paused"].includes(value) ? "text-bg-warning" : "text-bg-secondary"}`}>{Object.hasOwn(display,value) ? display[value] : "Chưa xác định"}</span>; }
